

# This config is a STUB! This should never be generated.
# Use the default lua config from https://github.com/hyprwm/Hyprland/blob/main/example/hyprland.lua

source = ~/.config/hypr/keybindings.conf

$mainMod = SUPER
$terminal = kitty
$fileManager = dolphin
$menu = ~/.config/rofi/launchers/type-2/launcher.sh
$browser = brave

bind = $mainMod, Q, exec, $terminal
bind = $mainMod, C, killactive,
bind = $mainMod, M, exec, command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch exit
bind = $mainMod, E, exec, $fileManager
bind = $mainMod, V, togglefloating,
bind = $mainMod, R, exec, $menu
bind = $mainMod, B, exec, $browser

input {
  kb_layout = br
  kb_variant = abnt2

  touchpad {
      natural_scroll = true
    }
} 

general {
  border_size = 2
}

decoration{
    rounding = 10
    rounding_power = 2

    active_opacity = 0.90
    inactive_opacity = 0.90
  }
